### ISSUE TITLE
Images are not replaced.

### ISSUE THREAD

**Issue by ghost** [WOVNio/wovnjava#11]
Retrieved image URL from API server is the following.

https://agile-fortress-79540.herokuapp.com/resources/images/banner-graphic.png;jsessionid=5qmal82dmraoez6stex25hug

**Comment by miniuchi** [comment]
Fixed wovnjava.

Also equalizer should implement this because there is the same problem when replacing by widget(JavaScript).

Is it better that scraping page by equalizer should remove jsessionid too?
