### ISSUE TITLE
Does HttpServletRequest.getScheme() always return "http" on Heroku?

### ISSUE THREAD

**Issue by ghost** [WOVNio/wovnjava#14]
When I registered the page to WOVN.io with "https" scheme, wovnjava does not replace images.

**Comment by miniuchi** [comment]
http://stackoverflow.com/questions/25911469/request-getscheme-is-returning-http-instead-of-returning-https-in-java

**Comment by miniuchi** [comment]
X-Forwarded-Proto:
https://devcenter.heroku.com/articles/http-routing
