### ISSUE TITLE
wovnjava does not work with sample page of Apache Tomcat.

### ISSUE THREAD

**Issue by masiuchi** [WOVNio/wovnjava#21]
- wovnjava works with sample application of Spring Framework on Heroku.
- wovnjava works with Tomcat 7 on my environment.

**Comment by masiuchi** [comment]
* In path mode, translated page (like https://localhost/ja) returns 404.
* Translation in backend does not work.
* Japanese characters are garbled.

**Comment by miniuchi** [comment]
This bug is still remaining.
> In path mode, translated page (like https://localhost/ja) returns 404.
> servlet filter cannot catch request to welcome-file-list.
