### ISSUE TITLE
Need to update languages to be on parity with WOVN.io

### ISSUE THREAD

**Issue by jsand-minimal** [WOVNio/wovnjava#55]
Please add any languages that are missing from WOVNjava.

This should include at the least Nepali, and may also Burmese and more.

**Comment by miniuchi** [comment]
Maybe, you should fix the following files.

* https://github.com/WOVNio/wovnjava/blob/0.1.9/src/main/java/com/github/wovnio/wovnjava/Lang.java
* https://github.com/WOVNio/wovnjava/blob/0.1.9/src/test/java/com/github/wovnio/wovnjava/LangTest.java

**Comment by miniuchi** [comment]
FYI: This commit added Bulgarian.

https://github.com/WOVNio/wovnjava/commit/718282339a8181c4d847dfce6d42fc5db685c307#diff-ac25d3814ea52b82cd40eed53722b44c

**Comment by jsand-minimal** [comment]
わざわざありがとうございます！！
